### ISSUE TITLE
Right Hand Margin on Tab need to be 10 px

### ISSUE THREAD

**Issue by jcockroft64** [jcockroft64/sierrahiking#79]
This needs to be done on the primary table (overview,joys, pains, logistics)
and the secondary table (campsites, permits, ....)

Please do this on the "A Northern JMT Extension"..

**Comment by russellelliott** [comment]
I noticed that none of the content in the primary tabs for that page are in a div the class `primary` and none of the content in the secondary tabs are in a div of the class `secondary`. Doing this sets the height of the tabs to a consistent value. A scrollbar also appears on the right in case of overflow. The inclusion of this adds padding to the right side of the content. The padding is styled in the `primary` and `secondary` classes to which not including those caused issues with the right padding. I think this is also due to me adding some padding to the left of the scrollbar for these kinds of tabs during my work in the summer.

Here is how to create content within the tabs with proper padding:
1. Go to the tab you want to add content to
2. Add your desired content in the visual text editor.
3. Copy paste the text from the visual text editor into a text to html converter. Here's an easy one you can use: https://wordhtml.com/
4. Copy the resulting text from the text to html converter.
5. Go back to the text editor and switch from visual mode to text mode.
6. Replace the text with an empty div with either class `primary` or `secondary` depending on which tabs it's in.
7. Paste the HTML text retrieved from step 3 into the empty div.

Also found and fixed a couple minor text mistakes:
- Replaced "7100n feet" with "7100 feet" in the "Campsites" tab.
- Removed extra space before the word "Go" in "Go for a swim"

Before:
Campsite One: Peeler Lake. The lake is 7.5 miles from the trailhead with a 2600 ft elevation gain. The trailhead is at 7100n ft, so I found this 7.5 miles, along with a full backpack is just about right for the first day.  Absolutely a gorgeous lake.  Sublime mornings.   Go for a swim.

After
Campsite One: Peeler Lake. The lake is 7.5 miles from the trailhead with a 2600 ft elevation gain. The trailhead is at **7100 ft**, so I found this 7.5 miles, along with a full backpack is just about right for the first day.  Absolutely a gorgeous lake.  Sublime mornings.  Go for a swim.

**Comment by russellelliott** [comment]
Another thing I could try is making the enter button press the return key. This can be done programmatically with Javascript.
https://stackoverflow.com/questions/596481/is-it-possible-to-simulate-key-press-events-programmatically

However, when interacting with the button, the mouse cursor doesn't indicate it's clickable. One solution is to add an event listener to the button so that clicking the button simulates the return key being pressed, thus making the button work.
https://www.w3schools.com/jsref/met_element_addeventlistener.asp

**Comment by jcockroft64** [comment]
I think i got it.   After inspecting in the text editor mode, i think all that needs to be done is add _**<div class="primary">**_ at the start of the text and then _**</div>**_ at the end of the text.       However, where do you set the border size of 10 pixels?   I think it should be 7.

**Comment by russellelliott** [comment]
Here is the CSS responsible for the internal padding within the tab. Note that the right padding is 0 because there is padding added within the primary and secondary div classes to accommodate the scrollbar. `!important` was used to ensure the CSS rules were used over the default ones for the tabs. 
```
/*Tab Widget CSS*/
.elementor-widget-tabs .elementor-tab-content{
    padding-right: 0px !important;
    /*make the other padding 7px*/
    padding-left:7px !important;
    padding-top:7px !important;
    padding-bottom:7px !important;
}
```
Here's what that padding looks like visually:
![Elementor Tab Padding 7px](https://user-images.githubusercontent.com/77514172/208721523-86889585-7e13-4041-aa68-b586565aa652.png)

As you requested, I set the padding within the tab to 7px.

**Comment by jcockroft64** [comment]
Ok got it.   I go to Elementor->Site Settings-> Custom CSS and then search for the /* Tab Widget CSS */  make the changes.  Thanks!

**Comment by jcockroft64** [comment]
Dang it, i messed up the actual problem description.   All along I meant to be talking about the right hand margin.

**Comment by jcockroft64** [comment]
Ok, i've changed the Custome CSS for the primary, secondary and Tab widgets to what i want them to be.
